name: CI

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: 'recursive'

      - uses: actions/cache@v4
        with:
          path: |
            ~/.nuget/packages
            ~/.cache/bepinex
          key: ${{ runner.os }}-nuget-${{ hashFiles('**/*.csproj', '**/packages.lock.json') }}
          restore-keys: |
            ${{ runner.os }}-nuget-

      - uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x

      - name: Build
        run: dotnet build --configuration Release

      - uses: actions/upload-artifact@v4
        with:
          name: TownOfExtra.dll
          path: |
            **/bin/Release/**/TownOfExtra.dll
            bin/Release/**/TownOfExtra.dll
          retention-days: 7
